--E-COMMERCE

CREATE TABLE USERS_GENERE(
    ID CHAR(1) NOT NULL PRIMARY KEY
    DESCR VARCHAR NOT NULL UNIQUE,
    DT_CREATED DATETIME NOT NULL,
);

CREATE TABLE PROFILES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PROFILE_NAME VARCHAR NOT NULL UNIQUE,
    DT_CREATED DATETIME NOT NULL;
);

CREATE TABLE USER_STATUS(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DESCR VARCHAR(255) NOT NULL,
    DT_CREATED DATETIME NOT NULL,
)
CREATE TABLE USERS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DT_BIRTH DATE NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASS VARCHAR(255) NOT NULL,
    FK_GENERE CHAR(1) NOT NULL,
    FK_USER_STATUS INT NOT NULL,
    DT_CREATED DATETIME NOT NULL,
    DT_UPDATED DATETIME,
    FOREIGN KEY (FK_GENERE) REFERENCES USERS_GENERE (ID),
    FOREIGN KEY (FK_USER_STATUS) REFERENCES USER_STATUS (ID)
);








CREATE TABLE PRODUCTS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCR VARCHAR(255) NOT NULL,
    PRICE DOUBLE NOT NULLM
    IMAGE VARCHAR(255),
    STATUS INT,
    DT_CREATED DATETIME NOT NULL,
    DT_UPDATED DATETIME,
    FK_USER_CREATED INT NOT NULL,
    ISDESTAC BOOLEAN
);
CREATE TABLE CHANNEL(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DESCR VARCHAR(255) NOT NULL,
    DT_CREATED DATETIME, NOT NULL,
)

CREATE TABLE CATEGORIES(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    SUBTILE VARCHAR(255)
    DT_CREATED DATETIME NOT NULL,
    DT_UPDATED DATETIME,
)

--CATEGORIES_PRODUCTS
CREATE TABLE CATEGORIES_PRODUCTS(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FK_PRODUCTS_ID INT NOT NULL,
    FK_CATEGORIES_ID INT NOT NULL
)

CREATE TABLE USERS_FIND(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    QUERY VARCHAR(255) NOT NULL,
    DT_CREATED DATETIME NOT NULL,
    FK_USERS_ID INT NOT NULL,
)

CREATE TABLE USERS_LIKE(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FK_USERS_ID INT NOT NULL,
    FK_PRODUCTS INT NOT NULL,
    LIKED BOOLEAN NOT NULL,
    DT_CREATED DATETIME NOT NULL,
    DT_UPDATED DATETIME NULL,
)
 --TABLE WITH AUTO RELASIONSHIP
CREATE TABLE MENU(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DESCR VARCHAR(255) NOT NULL,
    FK_MENU INT,
    DT_CREATED DATETIME NOT NULL,
    ISACTIVE BOOLEAN NOT NULL,
    ACTION VARCHAR(255) NOT NULL,
);

CREATE TABLE ITEMS_BASKET(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FK_PRODUCT,
    QUANTID,
    DT_CREATED
    DT_UPDATED
    FK_USERID
    fk_PROMOTION
    FK_STATUS_BASKET
)

CREATE TABLE STATUS BASKET(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DESCR
)
CREATE TABLE PROMOTION(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
    DESCOUNT DOUBLE,

)

CREATE TABLE SELS(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DT_PAYMENT DATE TIME,
    PAYMENT_TYPE, 
    STATUS PAYMENT,
    DT_CREATED
    DT_AUTHORIZED
)

CREATE TABLE PAYMENTT_TYPE

CREATE TABLE PAYMENTstatus(
    
)


