--TODO APP
CREATE TABLE STATUS(
    STATUS_CODE CHAR(1) NOT NULL PRIMARY KEY,
    DESCR VARCHAR(100)
);
INSERT INTO STATUS (STATUS_CODE, DESCR) VALUES ('A', 'ACTIVE');
INSERT INTO STATUS (STATUS_CODE, DESCR) VALUES ('F', 'DONE');
INSERT INTO STATUS (STATUS_CODE, DESCR) VALUES ('D', 'DELETED');


CREATE TABLE THINGS_TODO(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(50) NOT NULL,
    SUBTILE VARCHAR (100),
    DT_SCHEDULE DATE NOT NULL,
    TM_SCHEDULE TIME NOT NULL,
    STATUS CHAR(1) NOT NULL,
    DT_CREATED DATETIME,
);

INSERT INT ¡